export const judges = [
    {
        name: 'Sandip Palit',
        imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773408669/Sandip_Palit_lklccw.jpg',
        position: 'Senior Associate, PwC India',
        linkedinUrl: 'https://www.linkedin.com/in/sandip-palit/',
    },
    {
        name: 'Avik Agarwala',
        imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773408670/Avik_Agarwala_vhddfx.jpg',
        position: 'Systems Engineer, TCS',
        linkedinUrl: 'https://www.linkedin.com/in/avikagarwala/',
    },
    {
        name: 'Abhay Nath',
        imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773408668/Abhay_Nath_xiohco.jpg',
        position: 'Project Research Scientist-II, ISI Kolkata',
        linkedinUrl: 'https://www.linkedin.com/in/abhaynath001/',
    },
    {
        name: 'Swastik Bose',
        imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773408673/Swastik_Bose_vplhyt.jpg',
        position: 'Senior UX Designer, Zeise Digital',
        linkedinUrl: 'https://www.linkedin.com/in/swastik-bose007/',
    },
    {
        name: 'Ronit Banerjee',
        imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773408672/Ronit_Banerjee_efhrkx.jpg',
        position: 'DevOps Engineer, Keysight Technologies',
        linkedinUrl: 'https://www.linkedin.com/in/ronitbanerjee/',
    },
    {
        name: 'Ankit Kurmi',
        imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773408672/Ankit_Kurmi_zkxooo.jpg',
        position: 'SRE, Red Hat Inc.',
        linkedinUrl: 'https://www.linkedin.com/in/ankitk152/',
    },
    {
        name: 'Arya Chakraborty',
        imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773408672/ARYA_CHAKRABORTY_ptjgmk.jpg',
        position: 'AI Engineer, Namasys',
        linkedinUrl: 'https://www.linkedin.com/in/chakraborty-arya/',
    },
    {
        name: 'Saptarshi Bhattacharya',
        imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773408670/Saptarshi_Bhattacharya_ihmgpv.jpg',
        position: 'Executive, RPSG Ventures',
        linkedinUrl: 'https://www.linkedin.com/in/sbk2k1/',
    },
    {
        name: 'Sanglap Mridha',
        imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773408671/Sanglap_Mridha_v6alup.jpg',
        position: 'SDE l, Cozeva',
        linkedinUrl: 'https://www.linkedin.com/in/sanglapmridha/',
    },
    {
        name: 'Soham Banerjee',
        imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773408673/Soham_Banerjee_fz4uff.jpg',
        position: 'Software Engineer, HTCD',
        linkedinUrl: 'https://www.linkedin.com/in/soham4abc/',
    },
    {
        name: 'Supratim Dhara',
        imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773408671/Supratim_Dhara_pmp2xu.jpg',
        position: 'Mobile App Developer, Pegman',
        linkedinUrl: 'https://www.linkedin.com/in/supratimdhara/',
    },
    {
        name: 'Tamal Biswas',
        imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773408668/Tamal_Biswas_surq0u.jpg',
        position: 'SAP Basis Architect, Quantum Business Advisory',
        linkedinUrl: 'https://www.linkedin.com/in/tamal-biswas/',
    },
    {
        name: 'Bartick Maiti',
        imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773408668/bartick_maiti_fmbl0n.jpg',
        position: 'Backend Developer, Ringover',
        linkedinUrl: 'https://www.linkedin.com/in/bartick-maiti/',
    },
    {
        name: 'Imran Roshan',
        imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773408668/Imran_Roshan_aicehm.jpg',
        position: 'Cybersecurity and Cloud Lead, Senrysa Technologies Limited',
        linkedinUrl: 'https://www.linkedin.com/in/imranfosec/',
    },
    {
        name: 'Krishnendu Dakshi',
        imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773408668/Krishnendu_Dakshi_az4sfv.jpg',
        position: 'SDE, Tag Mango',
        linkedinUrl: 'https://www.linkedin.com/in/krishnendu-dakshi-624208224/',
    },
    {
        name: 'Shubhayu Majumdar',
        imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773408668/Shubhayu_Majumdar_lbmc77.jpg',
        position: 'Cloud Engineer, BlueVector AI',
        linkedinUrl: 'https://www.linkedin.com/in/shubhayu64/',
    },
    {
        name: 'Pritam Deb',
        imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773408668/pritam_deb_bsf3ms.jpg',
        position: 'Security Delivery Specialist, Accenture',
        linkedinUrl: 'https://www.linkedin.com/in/pritam-deb-3b6b0911b/',
    },
    {
        name: 'Sarnavo saha sardar',
        imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773512694/WhatsApp_Image_2026-03-14_at_23.50.55-removebg-preview_taxs9x.png',
        position: 'India Lead, Avalanche Team1',
        linkedinUrl: 'https://www.linkedin.com/in/sarnavo/',
    },
];
