export const mentors = [
  {
    name: 'Saptak Biswas',
    imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773407748/Saptak_Biswas_usvxbb.png',
    position: 'Devrel, Flutterflow , bindu',
    linkedinUrl: 'https://www.linkedin.com/in/saptak-biswas-50a834323',
  },
  {
    name: 'Deep Ghosh',
    imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773407746/DEEP_GHOSH_dlmoqg.jpg',
    position: 'SDE & AI Researcher, XorenAI',
    linkedinUrl: 'https://www.linkedin.com/in/deep-ghosh',
  },
  {
    name: 'Devesh Tulshyan',
    imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773407745/Devesh_Tulshyan_itgsx5.jpg',
    position: 'Fullstack (AI+Cloud) Engineer, Tata Consultancy Services',
    linkedinUrl: 'https://www.linkedin.com/in/devesh-tulshyan',
  },
  {
    name: 'Arpan Chowdhury',
    imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773407745/Arpan_Chowdhury_zmljwh.jpg',
    position: 'Frontend SDE Intern, Springer Capital',
    linkedinUrl: 'https://www.linkedin.com/in/arpan-chowdhury-775294251',
  },
  {
    name: 'Soumyadeep Bhowmik',
    imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773407743/Soumyadeep_Bhowmik_l8ewjd.jpg',
    position: 'Cofounder, Echomate.',
    linkedinUrl: 'https://www.linkedin.com/in/soumyadeep-bhowmik-87b318317',
  },
  {
    name: 'Akash Nath',
    imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773407743/Akash_Nath_cdewig.jpg',
    position: 'Backend AI Engineer, Craon.ai',
    linkedinUrl: 'https://www.linkedin.com/in/akash-nath29',
  },
  {
    name: 'Ayush Dhua',
    imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773407743/Ayush_Dhua_hreuua.jpg',
    position: 'Mobile App Developer Intern, AT&T',
    linkedinUrl: 'https://www.linkedin.com/in/ayushdhua',
  },
  {
    name: 'Debanjan Mondal',
    imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773407743/Debanjan_Mondal_zeh6p2.webp',
    position: 'DevRel Engineer, RiseIn',
    linkedinUrl: 'https://www.linkedin.com/in/debanjanmondal2005',
  },
  {
    name: 'Apabrita Sarkar',
    imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773407744/Apabrita_Sarkar_lzrpdf.png',
    position: 'Software analyst, Capgemini',
    linkedinUrl: 'https://www.linkedin.com/in/apabritasarkar',
  },
  {
    name: 'Rohit Debnath',
    imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773407746/Rohit_pnytha.jpg',
    position: 'intern, Intervue.io',
    linkedinUrl: 'https://www.linkedin.com/in/rohit-debnath',
  },
  {
    name: 'Souradip Pal',
    imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773407744/Souradip_Pal_knl703.jpg',
    position: 'AI Engineer, CannerAI',
    linkedinUrl: 'https://www.linkedin.com/in/souradip-pal-codes',
  },
  {
    name: 'Pratyay Chatterjee',
    imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773407745/Pratyay_Chatterjee_n9cxje.jpg',
    position: 'AI Engineer, Zyptr',
    linkedinUrl: 'https://www.linkedin.com/in/pratyaychatterjee',
  },
  {
    name: 'MD Asif',
    imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773407743/Md_Asif_yumnl0.jpg',
    position: 'System Software Engineer, AMI',
    linkedinUrl: 'https://www.linkedin.com/in/mdasif2003',
  },
  {
    name: 'Abhinaba Biswas',
    imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773409156/IMG20260220125335_1_-_Abhinaba_Biswas_mozflm.jpg',
    position: 'Co-Founder, MarsLab Studio',
    linkedinUrl: 'https://www.linkedin.com/in/abhinaba-biswas',
  },
  {
    name: 'Baivab Mukhopadhyay',
    imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773755600/IMG-20260316-WA0132_-_Baivab_Mukhopadhyay_yp376l.jpg',
    position: 'DevOps Engineer, Accuknox',
    linkedinUrl: 'https://www.linkedin.com/in/itsbaivab/',
  },
  {
    name: 'Snihita Nandi',
    imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773755601/Untitled_design_36_-_Snihita_Nandi_w3ef0j.png',
    position: 'Product & Visual Designer, XorenAI',
    linkedinUrl: 'https://www.linkedin.com/in/snihita-nandi/',
  },
  {
    name: 'Subham Bhattacharya',
    imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773755601/DSC_0016_1_1_-_Subham_Bhattacharya_kdqqze.jpg',
    position: 'Software Engineer, ABP',
    linkedinUrl: 'https://www.linkedin.com/in/subham2409/',
  },
  {
    name: 'Swastik Sarkar',
    imageUrl: 'https://res.cloudinary.com/dlxpcyiin/image/upload/v1773755600/Swastik_Sarkar_-_Swastik_Sarkar_dq4s72.jpg',
    position: 'SDE Intern, Veryze Technologies Pvt. Ltd.',
    linkedinUrl: 'https://www.linkedin.com/in/swastiksarkar001/',
  },
];
